name: customizable_folders
description: "Customizable Folders is an application for macOS that allows you to customize folders"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  desktop_drop: ^0.6.0
  image: ^4.5.4
  window_size: ^0.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/


flutter_launcher_icons:
  image_path: "assets/icon.png"
  macos:
    generate: true
    image_path: "assets/icon.png"